name: Publish @jravoux/akita

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        working-directory: dist/packages/akita
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
